porfolio:
    resource: "@PortfolioBundle/Controller/"
    type:     annotation
    prefix:   /

messagerie:
    resource: "@MessagerieBundle/Controller/"
    type:     annotation
    prefix:   /

evaluation:
    resource: "@EvaluationBundle/Controller/"
    type:     annotation
    prefix:   /

reclamation:
    resource: "@ReclamationBundle/Controller/"
    type:     annotation
    prefix:   /

publication:
    resource: "@PublicationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
